si7021.c File Reference
SI7021 Library for ESP-IDF framework main C file.
#include `si7021.h`
Functions
si7021_err_t si7021_init (si7021_config_t *config)
Initialize SI7021 sensor.
si7021_err_t __si7021_param_config (si7021_config_t *config)
Configure I2C Parameter for SI7021.
si7021_err_t __si7021_driver_config (si7021_config_t *config)
Configure I2C Driver for SI7021.
si7021_err_t si7021_check_availability ()
Check the availability of sensor.
float si7021_read_temperature ()
Read temperature value from sensor.
float si7021_read_humidity ()
Read Relative Humidity value from sensor.
uint16_t __si7021_read (uint8_t command)
Get data from sensors by issuing read command and read data return by sensor.
bool __is_crc_valid (uint16_t value, uint8_t crc)
Check data integrity with crc.
uint8_t si7021_soft_reset ()
Reset the sensor.
uint8_t __si7021_read_user_register ()
Read RH/T user register 1 from sensor.
uint8_t si7021_get_resolution ()
Get current resolution of sensor.
si7021_err_t si7021_set_resolution (uint8_t resolution)
Set the sensors resolution.
si7021_err_t __si7021_write_user_register (uint8_t value)
Write value to RH/T user register 1.
uint8_t si7021_read_firmware_rev ()
Read sensor firmware revision.
uint8_t si7021_read_vdd_status ()
Check sensors VDD.
uint8_t si7021_get_heater_status ()
Check sensors heater status.
uint8_t si7021_get_heater_register ()
Read heater register.
si7021_err_t si7021_set_heater_register (uint8_t value)
Set heater register.
si7021_err_t si7021_set_heater_status (uint8_t value)
Set heater status.
uint64_t get_electronic_id ()
Get sensor electronic id.
Variables
si7021_config_t __si7021_config
Detailed Description
SI7021 Library for ESP-IDF framework main C file.
Author
Le Nguyen Hoang Nhan
Date
19 May 2019
See also
https://www.silabs.com/documents/public/data-sheets/Si7021-A20.pdf
Copyright
Copyright (C) 2019 Le Nguyen Hoang Nhan. All rights reserved.
Function Documentation
__is_crc_valid()
bool __is_crc_valid (uint16_t value, uint8_t crc)
Check data integrity with crc.
Parameters
value 16bit (uint16_t) value that contain data return by sensors.
crc 8bit (uint8_t) value of crc data
Returns
boolean value, true if crc value is valid, otherwise false
Definition at line 142 of file si7021.c.
Referenced by __si7021_read().
__si7021_driver_config()
si7021_err_t __si7021_driver_config (si7021_config_t * config)
Configure I2C Driver for SI7021.
Note
Internal use only
Parameters
config Forwarded parameter from si7021_init(si7021_config_t *config)
Returns
SI7021_ERR_OK Success
SI7021_ERR_CONFIG Failed to install I2C parameters
Definition at line 61 of file si7021.c.
References SI7021_ERR_INSTALL, SI7021_ERR_OK, and si7021_config_t::si7021_port.
Referenced by si7021_init().
__si7021_param_config()
si7021_err_t __si7021_param_config (si7021_config_t * config)
Configure I2C Parameter for SI7021.
Note
Internal use only
Parameters
config Forwarded parameter from si7021_init(si7021_config_t *config)
Returns
SI7021_ERR_OK Success.
SI7021_ERR_CONFIG Failed to configure I2C parameter
Definition at line 50 of file si7021.c.
References si7021_config_t::sensors_config, SI7021_ERR_CONFIG, SI7021_ERR_OK, and si7021_config_t::si7021_port.
Referenced by si7021_init().
__si7021_read()
uint16_t __si7021_read (uint8_t cmd)
Get data from sensors by issuing read command and read data return by sensor.
Note
Internal use only
Parameters
cmd Command that will be sent to sensor
Returns
16bit value (uint16_t) contain data from sensors
Note
This function will print to console if crc value is invalid
Definition at line 102 of file si7021.c.
References __is_crc_valid(), SI7021_ADDR, and si7021_config_t::si7021_port.
Referenced by si7021_read_humidity(), and si7021_read_temperature().
__si7021_read_user_register()
uint8_t __si7021_read_user_register ()
Read RH/T user register 1 from sensor.
Note
Internal use only
Returns
8bit (unit8_t) value, contain content of user RH/T register
0 if failed to read
Definition at line 193 of file si7021.c.
References SI7021_ADDR, si7021_config_t::si7021_port, and SI7021_READRHT_REG_CMD.
Referenced by si7021_get_heater_status(), si7021_get_resolution(), si7021_read_vdd_status(), si7021_set_heater_status(), and si7021_set_resolution().
__si7021_write_user_register()
si7021_err_t __si7021_write_user_register (uint8_t value)
Write value to RH/T user register 1.
Note
Internal use only
Parameters
value Value to write to register
Returns
SI7021_ERR_OK Success
SI7021_ERR_INVALID_ARG Invalid arguments
SI7021_ERR_FAIL Failed to write
SI7021_ERR_INVALID_STATE Sensor is in invalid state
SI7021_ERR_TIMEOUT Timed out communicating with sensor
Definition at line 240 of file si7021.c.
References SI7021_ADDR, SI7021_ERR_FAIL, SI7021_ERR_INVALID_ARG, SI7021_ERR_INVALID_STATE, SI7021_ERR_OK, SI7021_ERR_TIMEOUT, si7021_config_t::si7021_port, and SI7021_WRITERHT_REG_CMD.
Referenced by si7021_set_heater_status(), and si7021_set_resolution().
get_electronic_id()
uint64_t get_electronic_id ()
Get sensor electronic id.
Returns
64bit (uint64_t) value contain sensor electronic id
Definition at line 370 of file si7021.c.
References SI7021_ADDR, SI7021_ID1_CMD, SI7021_ID2_CMD, and si7021_config_t::si7021_port.
si7021_check_availability()
si7021_err_t si7021_check_availability ()
Check the availability of sensor.
Returns
SI7021_ERR_OK Sensor detected and available
SI7021_ERR_NOTFOUND Sensor missing and/or not available
Definition at line 71 of file si7021.c.
References SI7021_ADDR, SI7021_ERR_NOTFOUND, SI7021_ERR_OK, and si7021_config_t::si7021_port.
Referenced by si7021_init().
si7021_get_heater_register()
uint8_t si7021_get_heater_register ()
Read heater register.
Returns
8bit (uint8_t) value contain content of heater register
0xF: 94.20mA
0x8: 51.96mA
0x4: 27.39mA
0x2: 15.24mA
0x1: 9.18mA
0x0: 3.09mA
Definition at line 311 of file si7021.c.
References SI7021_ADDR, si7021_config_t::si7021_port, and SI7021_READHEATER_REG_CMD.
si7021_get_heater_status()
uint8_t si7021_get_heater_status ()
Check sensors heater status.
Returns
8bit (uint8_t) value
SI7021_HEATER_ON HEATER is ON
SI7021_HEATER_OFF HEATER is OFF
Definition at line 304 of file si7021.c.
References __si7021_read_user_register(), SI7021_HEATER_OFF, and SI7021_HEATER_ON.
si7021_get_resolution()
uint8_t si7021_get_resolution ()
Get current resolution of sensor.
Returns
0x00: 12bit RH resolution, 14bit temperature resolution
0x01: 8bit RH resolution, 12bit temperature resolution
0x80: 10bit RH resolution, 13bit temperature resolution
0x81: 11bit RH resolution, 11bit temperature resolution
Definition at line 221 of file si7021.c.
References __si7021_read_user_register().
si7021_init()
si7021_err_t si7021_init (si7021_config_t * config)
Initialize SI7021 sensor.
Parameters
config si7021_config_t struct that contain sensors information and configuration
Returns
SI7021_ERR_OK Success.
SI7021_ERR_CONFIG Failed to configure I2C parameter, forwarded return from __si7021_param_config(si7021_config_t *config)
SI7021_ERR_INSTALL Failed to configure I2C Driver, forwarded return from __si7021_driver_config(si7021_config_t *config)
SI7021_ERR_NOTFOUND Sensor missing and/or not available, forwarded return from si7021_check_availability()
Definition at line 34 of file si7021.c.
References __si7021_driver_config(), __si7021_param_config(), si7021_check_availability(), and SI7021_ERR_OK.
si7021_read_firmware_rev()
uint8_t si7021_read_firmware_rev ()
Read sensor firmware revision.
Returns
8bit (uint8_t) value contain sensor firmware revision
0xFF: Firmware version 1.0
0x20: Firmware version 2.0
Definition at line 269 of file si7021.c.
References SI7021_ADDR, SI7021_FIRMVERS_CMD, and si7021_config_t::si7021_port.
si7021_read_humidity()
float si7021_read_humidity ()
Read Relative Humidity value from sensor.
Returns
float value, Relative Humidity in percentage
Definition at line 94 of file si7021.c.
References __si7021_read(), and SI7021_MEASRH_NOHOLD_CMD.
si7021_read_temperature()
float si7021_read_temperature ()
Read temperature value from sensor.
Returns
float value, temperature in Celsius
Definition at line 86 of file si7021.c.
References __si7021_read(), and SI7021_MEASTEMP_NOHOLD_CMD.
si7021_read_vdd_status()
uint8_t si7021_read_vdd_status ()
Check sensors VDD.
Returns
8bit (uint8_t) value
SI7021_VDD_OK VDD is OK
SI7021_VDD_LOW VDD is LOW
Note
Consider changing power supply when VDD is LOW, sensors may not work correctly
Definition at line 297 of file si7021.c.
References __si7021_read_user_register(), SI7021_VDD_LOW, and SI7021_VDD_OK.
si7021_set_heater_register()
si7021_err_t si7021_set_heater_register (uint8_t value)
Set heater register.
Parameters
value 8bit (uint8_t) value that will be written to heater register
0xF: 94.20mA
0x8: 51.96mA
0x4: 27.39mA
0x2: 15.24mA
0x1: 9.18mA
0x0: 3.09mA
Definition at line 338 of file si7021.c.
References SI7021_ADDR, SI7021_ERR_FAIL, SI7021_ERR_INVALID_ARG, SI7021_ERR_INVALID_STATE, SI7021_ERR_OK, SI7021_ERR_TIMEOUT, si7021_config_t::si7021_port, and SI7021_WRITEHEATER_REG_CMD.
si7021_set_heater_status()
si7021_err_t si7021_set_heater_status (uint8_t value)
Set heater status.
Parameters
value Heater status will be set to this
SI7021_HEATER_ON: HEATER will be turn on
SI7021_HEATER_OFF: HEATER will be turn off
Definition at line 361 of file si7021.c.
References __si7021_read_user_register(), __si7021_write_user_register(), SI7021_HEATER_OFF, and SI7021_HEATER_ON.
si7021_set_resolution()
si7021_err_t si7021_set_resolution (uint8_t resolution)
Set the sensors resolution.
Parameters
resolution The resolution will be set
Returns
SI7021_ERR_OK Success
SI7021_ERR_INVALID_ARG Invalid arguments
SI7021_ERR_FAIL Failed to write
SI7021_ERR_INVALID_STATE Sensor is in invalid state
SI7021_ERR_TIMEOUT Timed out communicating with sensor
Definition at line 225 of file si7021.c.
References __si7021_read_user_register(), and __si7021_write_user_register().
si7021_soft_reset()
uint8_t si7021_soft_reset ()
Reset the sensor.
Note
Reset will erase all setting, register...
Returns
SI7021_ERR_OK Success
SI7021_ERR_TIMEOUT Timed out communicating with sensor
SI7021_ERR_INVALID_STATE Sensor is in invalid state
SI7021_ERR_FAIL Failed
SI7021_ERR_INVALID_ARG Invalid arguments
Definition at line 167 of file si7021.c.
References SI7021_ADDR, SI7021_ERR_FAIL, SI7021_ERR_INVALID_ARG, SI7021_ERR_INVALID_STATE, SI7021_ERR_OK, SI7021_ERR_TIMEOUT, si7021_config_t::si7021_port, and SI7021_SOFT_RESET_CMD.
Variable Documentation
__si7021_config
si7021_config_t __si7021_config
Initial value:
= { .sensors_config = { .mode = I2C_MODE_MASTER,
        .sda_io_num = GPIO_NUM_22, .scl_io_num = GPIO_NUM_23, .sda_pullup_en =
                GPIO_PULLUP_ENABLE, .scl_pullup_en = GPIO_PULLUP_ENABLE,
        .master = { .clk_speed = 400000 }, }, .si7021_port = I2C_NUM_0 }
Definition at line 29 of file si7021.c.