include/si7021.h File Reference
SI7021 Library for ESP-IDF framework header file.
#include `esp_err.h`
#include `freertos/FreeRTOS.h`
#include `freertos/task.h`
#include `driver/i2c.h`
#include <stdlib.h>
#include <stdio.h>
Data Structures
struct si7021_config_t
SI7021 initialization parameter.
Macros
#define SI7021_ADDR 0x40
#define SI7021_MEASRH_HOLD_CMD 0xE5
#define SI7021_MEASRH_NOHOLD_CMD 0xF5
#define SI7021_MEASTEMP_HOLD_CMD 0xE3
#define SI7021_MEASTEMP_NOHOLD_CMD 0xF3
#define SI7021_READPREVTEMP_CMD 0xE0
#define SI7021_RESET_CMD 0xFE
#define SI7021_WRITERHT_REG_CMD 0xE6
#define SI7021_READRHT_REG_CMD 0xE7
#define SI7021_WRITEHEATER_REG_CMD 0x51
#define SI7021_READHEATER_REG_CMD 0x11
#define SI7021_ID1_CMD 0xFA0F
#define SI7021_ID2_CMD 0xFCC9
#define SI7021_FIRMVERS_CMD 0x84B8
#define SI7021_SOFT_RESET_CMD 0xFE
#define SI7021_ERR_OK 0x00
#define SI7021_ERR_CONFIG 0x01
#define SI7021_ERR_INSTALL 0x02
#define SI7021_ERR_NOTFOUND 0x03
#define SI7021_ERR_INVALID_ARG 0x04
#define SI7021_ERR_FAIL 0x05
#define SI7021_ERR_INVALID_STATE 0x06
#define SI7021_ERR_TIMEOUT 0x07
#define SI7021_HEATER_ON 0x01
#define SI7021_HEATER_OFF 0x00
Typedefs
typedef enum SI7021_RESOLUTION SI7021_RESOLUTION
Enum contain all valid Resolution configuration of sensor.
typedef enum SI7021_VDD_STATUS SI7021_VDD_STATUS
VDD status of sensor return type.
typedef struct si7021_config_t si7021_config_t
SI7021 initialization parameter.
typedef uint8_t si7021_err_t
Error type for return value.
Enumerations
enum SI7021_RESOLUTION { SI7021_12_14_RES = (uint8_t) 0x00,
SI7021_8_12_RES = (uint8_t) 0x01,
SI7021_10_13_RES = (uint8_t) 0x80,
SI7021_11_11_RES = (uint8_t) 0x81
 }
Enum contain all valid Resolution configuration of sensor.
enum SI7021_VDD_STATUS { SI7021_VDD_OK = (uint8_t) 0x01,
SI7021_VDD_LOW = (uint8_t) 0x00
 }
VDD status of sensor return type.
Functions
si7021_err_t si7021_init (si7021_config_t *config)
Initialize SI7021 sensor.
si7021_err_t __si7021_param_config (si7021_config_t *config)
Configure I2C Parameter for SI7021.
si7021_err_t __si7021_driver_config (si7021_config_t *config)
Configure I2C Driver for SI7021.
uint16_t __si7021_read (uint8_t cmd)
Get data from sensors by issuing read command and read data return by sensor.
bool __is_crc_valid (uint16_t value, uint8_t crc)
Check data integrity with crc.
si7021_err_t si7021_check_availability ()
Check the availability of sensor.
float si7021_read_temperature ()
Read temperature value from sensor.
float si7021_read_humidity ()
Read Relative Humidity value from sensor.
uint8_t __si7021_read_user_register ()
Read RH/T user register 1 from sensor.
si7021_err_t __si7021_write_user_register (uint8_t value)
Write value to RH/T user register 1.
SI7021_RESOLUTION si7021_get_resolution ()
Get current resolution of sensor.
si7021_err_t si7021_soft_reset ()
Reset the sensor.
si7021_err_t si7021_set_resolution (SI7021_RESOLUTION resolution)
Set the sensors resolution.
si7021_err_t si7021_set_heater_register (uint8_t value)
Set heater register.
si7021_err_t si7021_set_heater_status (uint8_t value)
Set heater status.
uint8_t si7021_get_heater_register ()
Read heater register.
uint8_t si7021_read_firmware_rev ()
Read sensor firmware revision.
SI7021_VDD_STATUS si7021_read_vdd_status ()
Check sensors VDD.
uint8_t si7021_get_heater_status ()
Check sensors heater status.
uint64_t get_electronic_id ()
Get sensor electronic id.
Variables
si7021_config_t __si7021_config
Internal variable for storing sensor information.
Detailed Description
SI7021 Library for ESP-IDF framework header file.
Author
Le Nguyen Hoang Nhan
Date
19 May 2019
See also
https://www.silabs.com/documents/public/data-sheets/Si7021-A20.pdf
Copyright
Copyright (C) 2019 Le Nguyen Hoang Nhan. All rights reserved.
Macro Definition Documentation
SI7021_ADDR
#define SI7021_ADDR 0x40
SI7021 default address
Definition at line 41 of file si7021.h.
Referenced by __si7021_read(), __si7021_read_user_register(), __si7021_write_user_register(), get_electronic_id(), si7021_check_availability(), si7021_get_heater_register(), si7021_read_firmware_rev(), si7021_set_heater_register(), and si7021_soft_reset().
SI7021_HEATER_OFF
#define SI7021_HEATER_OFF 0x00
Heater is OFF
Definition at line 103 of file si7021.h.
Referenced by si7021_get_heater_status(), and si7021_set_heater_status().
SI7021_HEATER_ON
#define SI7021_HEATER_ON 0x01
Heater is ON
Definition at line 102 of file si7021.h.
Referenced by si7021_get_heater_status(), and si7021_set_heater_status().
Typedef Documentation
si7021_config_t
typedef struct si7021_config_t si7021_config_t
SI7021 initialization parameter.
See also
__si7021_config
i2c.h::i2c_config_t
si7021_err_t
typedef uint8_t si7021_err_t
Error type for return value.
Definition at line 121 of file si7021.h.
SI7021_RESOLUTION
typedef enum SI7021_RESOLUTION SI7021_RESOLUTION
Enum contain all valid Resolution configuration of sensor.
Note
Only bit 0 and bit 7 matter, other bits will be ignored
SI7021_VDD_STATUS
typedef enum SI7021_VDD_STATUS SI7021_VDD_STATUS
VDD status of sensor return type.
Note
Consider changing power supply if VDD is LOW, the sensor may not work correctly
Enumeration Type Documentation
SI7021_RESOLUTION
enum SI7021_RESOLUTION
Enum contain all valid Resolution configuration of sensor.
Note
Only bit 0 and bit 7 matter, other bits will be ignored
Enumerator
SI7021_12_14_RES 12bit RH resolution, 14bit temperature resolution
SI7021_8_12_RES 8bit RH resolution, 12bit temperature resolution
SI7021_10_13_RES 10bit RH resolution, 13bit temperature resolution
SI7021_11_11_RES 11bit RH resolution, 11bit temperature resolution
Definition at line 87 of file si7021.h.
SI7021_VDD_STATUS
enum SI7021_VDD_STATUS
VDD status of sensor return type.
Note
Consider changing power supply if VDD is LOW, the sensor may not work correctly
Enumerator
SI7021_VDD_OK VDD is OK (>1.9 V)
SI7021_VDD_LOW VDD is LOW (1.9~1.8V)
Definition at line 97 of file si7021.h.
Function Documentation
__is_crc_valid()
bool __is_crc_valid (uint16_t value, uint8_t crc)
Check data integrity with crc.
Parameters
value 16bit (uint16_t) value that contain data return by sensors.
crc 8bit (uint8_t) value of crc data
Returns
boolean value, true if crc value is valid, otherwise false
Definition at line 142 of file si7021.c.
Referenced by __si7021_read().
__si7021_driver_config()
si7021_err_t __si7021_driver_config (si7021_config_t * config)
Configure I2C Driver for SI7021.
Note
Internal use only
Parameters
config Forwarded parameter from si7021_init(si7021_config_t *config)
Returns
SI7021_ERR_OK Success
SI7021_ERR_CONFIG Failed to install I2C parameters
Definition at line 61 of file si7021.c.
References SI7021_ERR_INSTALL, SI7021_ERR_OK, and si7021_config_t::si7021_port.
Referenced by si7021_init().
__si7021_param_config()
si7021_err_t __si7021_param_config (si7021_config_t * config)
Configure I2C Parameter for SI7021.
Note
Internal use only
Parameters
config Forwarded parameter from si7021_init(si7021_config_t *config)
Returns
SI7021_ERR_OK Success.
SI7021_ERR_CONFIG Failed to configure I2C parameter
Definition at line 50 of file si7021.c.
References si7021_config_t::sensors_config, SI7021_ERR_CONFIG, SI7021_ERR_OK, and si7021_config_t::si7021_port.
Referenced by si7021_init().
__si7021_read()
uint16_t __si7021_read (uint8_t cmd)
Get data from sensors by issuing read command and read data return by sensor.
Note
Internal use only
Parameters
cmd Command that will be sent to sensor
Returns
16bit value (uint16_t) contain data from sensors
Note
This function will print to console if crc value is invalid
Definition at line 102 of file si7021.c.
References __is_crc_valid(), SI7021_ADDR, and si7021_config_t::si7021_port.
Referenced by si7021_read_humidity(), and si7021_read_temperature().
__si7021_read_user_register()
uint8_t __si7021_read_user_register ()
Read RH/T user register 1 from sensor.
Note
Internal use only
Returns
8bit (unit8_t) value, contain content of user RH/T register
0 if failed to read
Definition at line 193 of file si7021.c.
References SI7021_ADDR, si7021_config_t::si7021_port, and SI7021_READRHT_REG_CMD.
Referenced by si7021_get_heater_status(), si7021_get_resolution(), si7021_read_vdd_status(), si7021_set_heater_status(), and si7021_set_resolution().
__si7021_write_user_register()
si7021_err_t __si7021_write_user_register (uint8_t value)
Write value to RH/T user register 1.
Note
Internal use only
Parameters
value Value to write to register
Returns
SI7021_ERR_OK Success
SI7021_ERR_INVALID_ARG Invalid arguments
SI7021_ERR_FAIL Failed to write
SI7021_ERR_INVALID_STATE Sensor is in invalid state
SI7021_ERR_TIMEOUT Timed out communicating with sensor
Definition at line 240 of file si7021.c.
References SI7021_ADDR, SI7021_ERR_FAIL, SI7021_ERR_INVALID_ARG, SI7021_ERR_INVALID_STATE, SI7021_ERR_OK, SI7021_ERR_TIMEOUT, si7021_config_t::si7021_port, and SI7021_WRITERHT_REG_CMD.
Referenced by si7021_set_heater_status(), and si7021_set_resolution().
get_electronic_id()
uint64_t get_electronic_id ()
Get sensor electronic id.
Returns
64bit (uint64_t) value contain sensor electronic id
Note
if error happen, return 0xFFFFFFFFFFFFFFFF
Definition at line 370 of file si7021.c.
References SI7021_ADDR, SI7021_ID1_CMD, SI7021_ID2_CMD, and si7021_config_t::si7021_port.
si7021_check_availability()
si7021_err_t si7021_check_availability ()
Check the availability of sensor.
Returns
SI7021_ERR_OK Sensor detected and available
SI7021_ERR_NOTFOUND Sensor missing and/or not available
Definition at line 71 of file si7021.c.
References SI7021_ADDR, SI7021_ERR_NOTFOUND, SI7021_ERR_OK, and si7021_config_t::si7021_port.
Referenced by si7021_init().
si7021_get_heater_register()
uint8_t si7021_get_heater_register ()
Read heater register.
Returns
8bit (uint8_t) value contain content of heater register
0xF: 94.20mA
0x8: 51.96mA
0x4: 27.39mA
0x2: 15.24mA
0x1: 9.18mA
0x0: 3.09mA
Definition at line 311 of file si7021.c.
References SI7021_ADDR, si7021_config_t::si7021_port, and SI7021_READHEATER_REG_CMD.
si7021_get_heater_status()
uint8_t si7021_get_heater_status ()
Check sensors heater status.
Returns
8bit (uint8_t) value
SI7021_HEATER_ON HEATER is ON
SI7021_HEATER_OFF HEATER is OFF
Definition at line 304 of file si7021.c.
References __si7021_read_user_register(), SI7021_HEATER_OFF, and SI7021_HEATER_ON.
si7021_get_resolution()
SI7021_RESOLUTION si7021_get_resolution ()
Get current resolution of sensor.
Returns
0x00: 12bit RH resolution, 14bit temperature resolution
0x01: 8bit RH resolution, 12bit temperature resolution
0x80: 10bit RH resolution, 13bit temperature resolution
0x81: 11bit RH resolution, 11bit temperature resolution
Definition at line 221 of file si7021.c.
References __si7021_read_user_register().
si7021_init()
si7021_err_t si7021_init (si7021_config_t * config)
Initialize SI7021 sensor.
Parameters
config si7021_config_t struct that contain sensors information and configuration
Returns
SI7021_ERR_OK Success.
SI7021_ERR_CONFIG Failed to configure I2C parameter, forwarded return from __si7021_param_config(si7021_config_t *config)
SI7021_ERR_INSTALL Failed to configure I2C Driver, forwarded return from __si7021_driver_config(si7021_config_t *config)
SI7021_ERR_NOTFOUND Sensor missing and/or not available, forwarded return from si7021_check_availability()
Definition at line 34 of file si7021.c.
References __si7021_driver_config(), __si7021_param_config(), si7021_check_availability(), and SI7021_ERR_OK.
si7021_read_firmware_rev()
uint8_t si7021_read_firmware_rev ()
Read sensor firmware revision.
Returns
8bit (uint8_t) value contain sensor firmware revision
0xFF: Firmware version 1.0
0x20: Firmware version 2.0
Definition at line 269 of file si7021.c.
References SI7021_ADDR, SI7021_FIRMVERS_CMD, and si7021_config_t::si7021_port.
si7021_read_humidity()
float si7021_read_humidity ()
Read Relative Humidity value from sensor.
Returns
float value, Relative Humidity in percentage
Definition at line 94 of file si7021.c.
References __si7021_read(), and SI7021_MEASRH_NOHOLD_CMD.
si7021_read_temperature()
float si7021_read_temperature ()
Read temperature value from sensor.
Returns
float value, temperature in Celsius
Definition at line 86 of file si7021.c.
References __si7021_read(), and SI7021_MEASTEMP_NOHOLD_CMD.
si7021_read_vdd_status()
SI7021_VDD_STATUS si7021_read_vdd_status ()
Check sensors VDD.
Returns
8bit (uint8_t) value
SI7021_VDD_OK VDD is OK
SI7021_VDD_LOW VDD is LOW
Note
Consider changing power supply when VDD is LOW, sensors may not work correctly
Definition at line 297 of file si7021.c.
References __si7021_read_user_register(), SI7021_VDD_LOW, and SI7021_VDD_OK.
si7021_set_heater_register()
si7021_err_t si7021_set_heater_register (uint8_t value)
Set heater register.
Parameters
value 8bit (uint8_t) value that will be written to heater register
0xF: 94.20mA
0x8: 51.96mA
0x4: 27.39mA
0x2: 15.24mA
0x1: 9.18mA
0x0: 3.09mA
Definition at line 338 of file si7021.c.
References SI7021_ADDR, SI7021_ERR_FAIL, SI7021_ERR_INVALID_ARG, SI7021_ERR_INVALID_STATE, SI7021_ERR_OK, SI7021_ERR_TIMEOUT, si7021_config_t::si7021_port, and SI7021_WRITEHEATER_REG_CMD.
si7021_set_heater_status()
si7021_err_t si7021_set_heater_status (uint8_t value)
Set heater status.
Parameters
value Heater status will be set to this
SI7021_HEATER_ON: HEATER will be turn on
SI7021_HEATER_OFF: HEATER will be turn off
Definition at line 361 of file si7021.c.
References __si7021_read_user_register(), __si7021_write_user_register(), SI7021_HEATER_OFF, and SI7021_HEATER_ON.
si7021_set_resolution()
si7021_err_t si7021_set_resolution (SI7021_RESOLUTION resolution)
Set the sensors resolution.
Parameters
resolution The resolution will be set
Returns
SI7021_ERR_OK Success
SI7021_ERR_INVALID_ARG Invalid arguments
SI7021_ERR_FAIL Failed to write
SI7021_ERR_INVALID_STATE Sensor is in invalid state
SI7021_ERR_TIMEOUT Timed out communicating with sensor
Definition at line 225 of file si7021.c.
References __si7021_read_user_register(), and __si7021_write_user_register().
si7021_soft_reset()
si7021_err_t si7021_soft_reset ()
Reset the sensor.
Note
Reset will erase all setting, register...
Returns
SI7021_ERR_OK Success
SI7021_ERR_TIMEOUT Timed out communicating with sensor
SI7021_ERR_INVALID_STATE Sensor is in invalid state
SI7021_ERR_FAIL Failed
SI7021_ERR_INVALID_ARG Invalid arguments
Definition at line 167 of file si7021.c.
References SI7021_ADDR, SI7021_ERR_FAIL, SI7021_ERR_INVALID_ARG, SI7021_ERR_INVALID_STATE, SI7021_ERR_OK, SI7021_ERR_TIMEOUT, si7021_config_t::si7021_port, and SI7021_SOFT_RESET_CMD.
Variable Documentation
__si7021_config
si7021_config_t __si7021_config
Internal variable for storing sensor information.
Definition at line 126 of file si7021.h.